apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: "9092"
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: jmx-exporter
          image: bitnami/jmx-exporter:latest
          args: [ "12345", "/opt/jmx_exporter/config.yaml" ]
          ports:
            - name: prom
              containerPort: 12345
          volumeMounts:
            - mountPath: /opt/jmx_exporter/config.yaml
              name: jmx-exporter-cfg-volume
              readOnly: true
              subPath: config.yaml
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
          resources:
            requests:
              cpu: "4"
              memory: 8Gi
            limits:
              cpu: "4"
              memory: 8Gi
          env:
            - name: "KAFKA_NODE_ID"
              value: "1"
            - name: "KAFKA_PROCESS_ROLES"
              value: "broker,controller"
            - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: "KAFKA_CONTROLLER_QUORUM_VOTERS"
              value: "1@kafka-0:9093"
            - name: "KAFKA_LISTENERS"
              value: "PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094"
            - name: "KAFKA_INTER_BROKER_LISTENER_NAME"
              value: "PLAINTEXT"
            - name: "KAFKA_ADVERTISED_LISTENERS"
              value: "PLAINTEXT://kafka-svc:9092,PLAINTEXT_HOST://localhost:9092"
            - name: "KAFKA_CONTROLLER_LISTENER_NAMES"
              value: "CONTROLLER"
            - name: "CLUSTER_ID"
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
              value: "1"
            - name: "KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS"
              value: "0"
            - name: "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR"
              value: "1"
            - name: "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR"
              value: "1"
            - name: KAFKA_LOG_DIR
              value: /mnt/kafka
            - name: JMX_PORT
              value: "10092"
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx2g -Xms2g"
          volumeMounts:
            - mountPath: /mnt/kafka
              name: data
      volumes:
        - name: jmx-exporter-cfg-volume
          configMap:
            name: jmx-exporter-cfg-cm
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: "{YOUR_STORAGE_CLASS_NAME}"
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-exporter-cfg-cm
data:
  config.yaml: |-
    hostPort: localhost:10092
    lowercaseOutputName: true
    rules:
    ## Memory
    - pattern: 'java.lang<type=Memory><(Heap|NonHeap)MemoryUsage>(\w+):'
      attrNameSnakeCase: true
      name: java_lang_memory_memory_usage_$2
      type: GAUGE
      labels:
        area: $1
  
    - pattern: 'java.lang<type=MemoryPool, name=(.*)><CollectionUsage>(\w*):'
      attrNameSnakeCase: true
      name: java_lang_memorypool_collection_usage_$2
      type: GAUGE
      labels:
        name: $1
  
    - pattern: 'java.lang<type=MemoryPool, name=(.*)><Usage>(\w*):'
      attrNameSnakeCase: true
      name: java_lang_memorypool_usage_$2
      type: GAUGE
      labels:
        name: $1
  
    - pattern: 'java.lang<type=MemoryPool, name=(.*)><PeakUsage>(\w*):'
      attrNameSnakeCase: true
      name: java_lang_memorypool_peak_usage_$2
      type: GAUGE
      labels:
        name: $1
    
    # JVM Thread
    - attrNameSnakeCase: true
      pattern: 'java.lang<type=Threading><>(\w*thread_count):'
      name: java_lang_threading_$1
      type: GAUGE
